/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.6
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "offscreen"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "offscreen"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "0.0.0"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * backimg_arg;	/**< @brief the back image.  */
  char * backimg_orig;	/**< @brief the back image original value given at command line.  */
  const char *backimg_help; /**< @brief the back image help description.  */
  char * frontimg_arg;	/**< @brief the front image.  */
  char * frontimg_orig;	/**< @brief the front image original value given at command line.  */
  const char *frontimg_help; /**< @brief the front image help description.  */
  int winwidth_arg;	/**< @brief windows  width, equal video  width (default='640').  */
  char * winwidth_orig;	/**< @brief windows  width, equal video  width original value given at command line.  */
  const char *winwidth_help; /**< @brief windows  width, equal video  width help description.  */
  int winheight_arg;	/**< @brief windows height, equal video height (default='480').  */
  char * winheight_orig;	/**< @brief windows height, equal video height original value given at command line.  */
  const char *winheight_help; /**< @brief windows height, equal video height help description.  */
  int framerate_arg;	/**< @brief video frame rate (default='25').  */
  char * framerate_orig;	/**< @brief video frame rate original value given at command line.  */
  const char *framerate_help; /**< @brief video frame rate help description.  */
  int duration_arg;	/**< @brief video play duration (default='5').  */
  char * duration_orig;	/**< @brief video play duration original value given at command line.  */
  const char *duration_help; /**< @brief video play duration help description.  */
  int start_arg;	/**< @brief genenate image start number (default='0').  */
  char * start_orig;	/**< @brief genenate image start number original value given at command line.  */
  const char *start_help; /**< @brief genenate image start number help description.  */
  int direction_flag;	/**< @brief rotate clock direction (default=off).  */
  const char *direction_help; /**< @brief rotate clock direction help description.  */
  char * outpath_arg;	/**< @brief the output image file path (default='./').  */
  char * outpath_orig;	/**< @brief the output image file path original value given at command line.  */
  const char *outpath_help; /**< @brief the output image file path help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int backimg_given ;	/**< @brief Whether backimg was given.  */
  unsigned int frontimg_given ;	/**< @brief Whether frontimg was given.  */
  unsigned int winwidth_given ;	/**< @brief Whether winwidth was given.  */
  unsigned int winheight_given ;	/**< @brief Whether winheight was given.  */
  unsigned int framerate_given ;	/**< @brief Whether framerate was given.  */
  unsigned int duration_given ;	/**< @brief Whether duration was given.  */
  unsigned int start_given ;	/**< @brief Whether start was given.  */
  unsigned int direction_given ;	/**< @brief Whether direction was given.  */
  unsigned int outpath_given ;	/**< @brief Whether outpath was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
